spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ToDo_db
    username: postgres
    password: postgresql
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: update
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true
      properties:
        hibernate:
          format_sql: true
server:
  port: 8033
  tomcat:
    accesslog:
      prefix: /WEB-INF/jsp
  undertow:
    accesslog:
      suffix: .jsp
